"""ACCEPTANCE E2E — two live agents meet on the real Hermix backend.

This is the product's definition of done. It boots the real backend as a
subprocess, then drives two independent agents ("gus-herald" and "mira-herald")
all the way through the network handshake:

    register -> publish card -> pull signals (cross-match) ->
    gus messages mira -> mira answers via the ENVOY membrane -> gus reads reply.

Each agent uses its OWN HttpTransport instance with its OWN api key, exactly as
two separate installs would. mira's reply is generated by the same envoy module
the plugin ships (with a fake, deterministic llm callable) so the membrane is
exercised end-to-end.

Run:  python e2e/two_agents.py         (from the repo root)
Exit: 0 on success, non-zero on any assertion / setup failure. The uvicorn
      subprocess is always terminated in a finally block.
"""
import importlib.util
import os
import pathlib
import socket
import subprocess
import sys
import tempfile
import time

# --- make the plugin importable as the canonical `hermix` package ----------
ROOT = pathlib.Path(__file__).resolve().parent.parent
if "hermix" not in sys.modules:
    _spec = importlib.util.spec_from_file_location(
        "hermix", ROOT / "__init__.py", submodule_search_locations=[str(ROOT)]
    )
    _mod = importlib.util.module_from_spec(_spec)
    sys.modules["hermix"] = _mod
    _spec.loader.exec_module(_mod)

from hermix import profile, envoy  # noqa: E402
from hermix.client import HttpTransport, HermixClient  # noqa: E402

HOST = "127.0.0.1"
PORT = 8787
BASE_URL = f"http://{HOST}:{PORT}"
BACKEND_DIR = ROOT / "backend"

REPLY_TOKEN = "MIRA-REPLY-7F3A"  # unique marker so we can find the reply again


# ---------------------------------------------------------------------------
# transcript helper
# ---------------------------------------------------------------------------
def say(who: str, what: str) -> None:
    print(f"  [{who:>11}] {what}", flush=True)


def banner(text: str) -> None:
    print(f"\n=== {text} ===", flush=True)


# ---------------------------------------------------------------------------
# backend lifecycle
# ---------------------------------------------------------------------------
def start_backend():
    """Launch `python -m uvicorn app:app --port 8787` with cwd=backend/ and a
    temp HERMIX_DB. Poll the TCP port until it accepts connections."""
    if not (BACKEND_DIR / "app.py").exists():
        raise RuntimeError(
            f"backend/app.py not found under {BACKEND_DIR}. The backend is built "
            "by a separate agent; run this once app:app exists."
        )

    tmp_db = tempfile.NamedTemporaryFile(prefix="hermix-e2e-", suffix=".db", delete=False)
    tmp_db.close()

    env = dict(os.environ)
    env["HERMIX_DB"] = tmp_db.name
    env.setdefault("PYTHONIOENCODING", "utf-8")

    say("harness", f"starting backend (HERMIX_DB={tmp_db.name})")
    proc = subprocess.Popen(
        [sys.executable, "-m", "uvicorn", "app:app", "--host", HOST, "--port", str(PORT),
         "--log-level", "warning"],
        cwd=str(BACKEND_DIR),
        env=env,
    )

    deadline = time.time() + 30
    while time.time() < deadline:
        if proc.poll() is not None:
            raise RuntimeError(f"backend exited early with code {proc.returncode}")
        try:
            with socket.create_connection((HOST, PORT), timeout=0.5):
                say("harness", "backend is accepting connections")
                # tiny grace period for app startup to finish wiring routes
                time.sleep(0.4)
                return proc, tmp_db.name
        except OSError:
            time.sleep(0.25)

    proc.terminate()
    raise RuntimeError("backend did not become ready within 30s")


def stop_backend(proc) -> None:
    if proc is None:
        return
    say("harness", "terminating backend subprocess")
    proc.terminate()
    try:
        proc.wait(timeout=10)
    except subprocess.TimeoutExpired:
        proc.kill()
        proc.wait(timeout=5)


# ---------------------------------------------------------------------------
# agent helpers
# ---------------------------------------------------------------------------
def make_agent(handle, represents, offer, need, guilds):
    """Register a fresh account, return (client, card) wired to its own key."""
    # Registration is unauthenticated -> transport with an empty key.
    boot = HttpTransport(BASE_URL, "")
    resp = boot.register(handle, represents)
    api_key = resp["api_key"]
    assert api_key, f"{handle}: register returned no api_key"
    say(handle, f"registered, got api_key={api_key[:8]}…")

    # Each agent now talks through ITS OWN keyed transport instance.
    transport = HttpTransport(BASE_URL, api_key)
    client = HermixClient(transport)

    card = profile.PublicCard(
        handle=handle, represents=represents,
        offer=offer, need=need, guilds=guilds,
    )
    client.publish_profile(card.public_dict())
    say(handle, f"published card (offer={offer}, need={need})")
    return client, card


def fake_llm(system: str, user: str) -> str:
    """Deterministic stand-in for ctx.llm inside the envoy. It only ever sees the
    card-derived system prompt + the sanitized, framed inbound query."""
    return (f"Yes — happy to collaborate on that. My human does AI video and 3D "
            f"worlds. ({REPLY_TOKEN})")


# ---------------------------------------------------------------------------
# the acceptance flow
# ---------------------------------------------------------------------------
def run() -> None:
    banner("Register + publish two agents")
    gus_client, gus_card = make_agent(
        "gus-herald",
        "a creative technologist in AI film, games, agents, 3D worlds",
        offer=["ai video", "3d worlds", "agent plugins"],
        need=["music visuals", "collaborators", "paid work"],
        guilds=["ai-video", "agents"],
    )
    mira_client, mira_card = make_agent(
        "mira-herald",
        "an AI music-video artist",
        offer=["music visuals", "beat-synced edits"],
        need=["ai video", "3d worlds"],
        guilds=["music", "ai-video"],
    )

    banner("Pull signals — each must see the other")
    gus_signals = gus_client.list_signals("gus-herald")
    mira_signals = mira_client.list_signals("mira-herald")
    say("gus-herald", f"signals: {[s.get('agent') for s in gus_signals]}")
    say("mira-herald", f"signals: {[s.get('agent') for s in mira_signals]}")

    gus_matches = {s.get("agent") for s in gus_signals if s.get("kind") == "match"}
    mira_matches = {s.get("agent") for s in mira_signals if s.get("kind") == "match"}
    assert "mira-herald" in gus_matches, f"gus did not match mira; saw {gus_matches}"
    assert "gus-herald" in mira_matches, f"mira did not match gus; saw {mira_matches}"
    say("harness", "OK — reciprocal match confirmed")

    banner("gus -> mira: send a message")
    outbound = "Would you be open to collaborating on an AI music video?"
    gus_client.send_message("mira-herald", outbound)
    say("gus-herald", f"sent to @mira-herald: {outbound!r}")

    banner("mira drains inbound and answers via the ENVOY membrane")
    inbound = mira_client.list_inbound("mira-herald")
    assert inbound, "mira's inbox was empty; expected gus's message"
    msg = inbound[0]
    say("mira-herald", f"inbound {msg['id']} from @{msg['from']}: {msg['query']!r}")
    reply = envoy.respond(mira_card, msg["query"], fake_llm)
    mira_client.post_reply(msg["id"], reply)
    say("mira-herald", f"envoy replied: {reply!r}")

    banner("gus drains inbound and reads mira's reply")
    gus_inbox = gus_client.list_inbound("gus-herald")
    say("gus-herald", f"inbound: {gus_inbox}")
    haystack = " ".join(
        str(v) for m in gus_inbox for v in m.values()
    )
    assert REPLY_TOKEN in haystack, (
        "gus did not receive mira's reply. The backend must route a /v1/reply "
        "back into the original sender's /v1/inbound. Got: " + repr(gus_inbox)
    )
    say("harness", "OK — gus received mira's reply")

    banner("ACCEPTANCE PASSED ✔")


def main() -> int:
    proc = None
    db_path = None
    try:
        proc, db_path = start_backend()
        run()
        return 0
    except AssertionError as e:
        print(f"\nASSERTION FAILED: {e}", file=sys.stderr, flush=True)
        return 1
    except Exception as e:  # setup/backend failures
        print(f"\nE2E ERROR: {e}", file=sys.stderr, flush=True)
        return 2
    finally:
        stop_backend(proc)
        if db_path and os.path.exists(db_path):
            try:
                os.remove(db_path)
            except OSError:
                pass


if __name__ == "__main__":
    sys.exit(main())
